/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.scrollpane;

import com.mycompany.scrollpane.EstadisticasImagen;
import com.mycompany.scrollpane.ImageHandler;
import com.mycompany.scrollpane.Lienzo;
import java.awt.Dimension;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.opencv.core.Core;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS;
import static javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER;

/**
 *
 * @author jorge
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private static File fichero;
    private JFileChooser fc;
    private MiListener listener;
    private JScrollBar barraVertical;
    private JScrollBar barraHorizontal;
    private FileNameExtensionFilter filter;
    private ButtonGroup buttonGroup;
    private JViewport vp;
    public MainFrame() {
        nu.pattern.OpenCV.loadShared(); System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        initComponents();
        initialConfig();
      
        
    }
    
    public static void refreshStats(){
        int[] max=EstadisticasImagen.getMaximo();
        int[] min=EstadisticasImagen.getMinimo();
        int[] prom=EstadisticasImagen.getPromedio();
        
        redMaxLabel.setText(Integer.toString(max[0]));
        greenMaxLabel.setText(Integer.toString(max[1]));
        blueMaxLabel.setText(Integer.toString(max[2]));
        
        redMinLabel.setText(Integer.toString(min[0]));
        greenMinLabel.setText(Integer.toString(min[1]));
        blueMinLabel.setText(Integer.toString(min[2]));
        
        redAveLabel.setText(Integer.toString(prom[0]));
        greenAveLabel.setText(Integer.toString(prom[1]));
        blueAveLabel.setText(Integer.toString(prom[2]));
    }
    
     private void initialConfig(){
        fc = new JFileChooser();

        buttonGroup= new ButtonGroup();
        listener= new MiListener();
        
        
        barraVertical= jScrollPane1.getVerticalScrollBar();
        barraHorizontal = jScrollPane1.getHorizontalScrollBar();
        
        
        barraVertical.addAdjustmentListener(listener);
        barraHorizontal.addAdjustmentListener(listener);
        
        vp = jScrollPane1.getViewport();
        listener.setViewPort(vp);
        setDropTarget();
    
      
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        autores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo1 = new com.mycompany.scrollpane.Lienzo();
        jPanel2 = new javax.swing.JPanel();
        redLabel = new javax.swing.JLabel();
        greenLabel = new javax.swing.JLabel();
        blueLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        minLabel = new javax.swing.JLabel();
        AverageLabel = new javax.swing.JLabel();
        redMaxLabel = new javax.swing.JLabel();
        redMinLabel = new javax.swing.JLabel();
        redAveLabel = new javax.swing.JLabel();
        greenMaxLabel = new javax.swing.JLabel();
        greenMinLabel = new javax.swing.JLabel();
        greenAveLabel = new javax.swing.JLabel();
        blueMaxLabel = new javax.swing.JLabel();
        blueMinLabel = new javax.swing.JLabel();
        blueAveLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        autores.setText("Jorge Rodrigo Blanco Anton y Grabirel Herandez Salazar");

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        redLabel.setText("Rojo:");

        greenLabel.setText("Verde:");

        blueLabel.setText("Azul:");

        maxLabel.setText("Máximo");

        minLabel.setText("Mínimo");

        AverageLabel.setText("Promedio");

        redMaxLabel.setText("0");

        redMinLabel.setText("0");

        redAveLabel.setText("0");

        greenMaxLabel.setText("0");

        greenMinLabel.setText("0");

        greenAveLabel.setText("0");

        blueMaxLabel.setText("0");

        blueMinLabel.setText("0");

        blueAveLabel.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redLabel)
                    .addComponent(blueLabel)
                    .addComponent(greenLabel))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueMaxLabel)
                            .addComponent(greenMaxLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxLabel)
                            .addComponent(redMaxLabel))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minLabel)
                    .addComponent(redMinLabel)
                    .addComponent(greenMinLabel)
                    .addComponent(blueMinLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AverageLabel)
                    .addComponent(redAveLabel)
                    .addComponent(greenAveLabel)
                    .addComponent(blueAveLabel))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxLabel)
                    .addComponent(minLabel)
                    .addComponent(AverageLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redLabel)
                    .addComponent(redMaxLabel)
                    .addComponent(redMinLabel)
                    .addComponent(redAveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenLabel)
                    .addComponent(greenMaxLabel)
                    .addComponent(greenMinLabel)
                    .addComponent(greenAveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel)
                    .addComponent(blueMaxLabel)
                    .addComponent(blueMinLabel)
                    .addComponent(blueAveLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenu.setText("Archicos");

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        fileMenu.add(abrir);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fileMenu.add(salir);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(autores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(autores)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        setFileChooser();
        int res = fc.showOpenDialog(null);
        if(res==JFileChooser.APPROVE_OPTION){
           openImageActions(fc.getSelectedFile());
        }   
    }//GEN-LAST:event_abrirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       dispose();
    }//GEN-LAST:event_salirActionPerformed
    
  
    private void setFileChooser() {
        fc.setAcceptAllFileFilterUsed(false);
        filter = new FileNameExtensionFilter("Imágenes (png, jpg, jpeg, bmp)","png","jpg","jpeg","bmp");
        fc.addChoosableFileFilter(filter);
    }
    private void setDropTarget() {
        lienzo1.setDropTarget(new DropTarget(){
            public synchronized void drop(DropTargetDropEvent evt){
                try{
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>)
                        evt.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    for (File file: droppedFiles){
                       // openImageActions(file);
                    }
                      setBounds(0,0,900, 900);
                }catch(Exception e){
                    
                }
            }
        });
    }    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AverageLabel;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JLabel autores;
    private static javax.swing.JLabel blueAveLabel;
    private javax.swing.JLabel blueLabel;
    private static javax.swing.JLabel blueMaxLabel;
    private static javax.swing.JLabel blueMinLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.Box.Filler filler1;
    private static javax.swing.JLabel greenAveLabel;
    private javax.swing.JLabel greenLabel;
    private static javax.swing.JLabel greenMaxLabel;
    private static javax.swing.JLabel greenMinLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mycompany.scrollpane.Lienzo lienzo1;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JLabel minLabel;
    private static javax.swing.JLabel redAveLabel;
    private javax.swing.JLabel redLabel;
    private static javax.swing.JLabel redMaxLabel;
    private static javax.swing.JLabel redMinLabel;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    private void openImageActions(File file){
        
        try{
            fichero=file;
            Dimension dimension=ImageHandler.openImage(file);
      
            listener.setFile(file);
            lienzo1.repaint();
        
            if(dimension.getWidth()<300 || dimension.getHeight()<300 ){
                lienzo1.removeImage();
                lienzo1.repaint();

                JOptionPane.showMessageDialog(this, "La imagen es demasiado pequeña");
                dispose();
            }
            if(dimension.getWidth()<900 || dimension.getHeight()<900 ){
                this.setSize((int)dimension.getWidth()+30,(int)dimension.getHeight()+230);
                  this.setMaximumSize(new Dimension((int)dimension.getWidth()+30,(int)dimension.getHeight()+230));

            }else{
                this.setSize(900, 900); 
                this.setMaximumSize(new Dimension(900,900));
            }
            
           //  this.setResizable(false);
        }catch(Exception e){
            
        }

    }
 
}
